import { text, type LocalizedText } from "@codigdex/game-core/i18n/locale";

const names = (entries: Readonly<Record<string, string>>): Readonly<Record<string, LocalizedText>> =>
  Object.fromEntries(
    Object.entries(entries).map(([id, ko]) => [
      id,
      text(
        ko,
        id.split("-").map((part) => part.charAt(0).toUpperCase() + part.slice(1)).join(" ")
      ),
    ])
  );

/** Korean display names paired with the canonical English asset names. */
export const CAREER_MONSTER_NAMES = names({
  "structure-sprout": "구조 새싹",
  "style-shell": "스타일 셸",
  "cascade-weaver": "캐스케이드 위버",
  "breakpoint-knight": "브레이크포인트 기사",
  "responsive-layout-paladin": "반응형 레이아웃 성기사",
  "script-spark": "스크립트 불꽃",
  "callback-fox": "콜백 여우",
  "event-spark": "이벤트 불꽃",
  "promise-seer": "프로미스 예언자",
  "async-oracle": "비동기 오라클",
  "message-pair": "메시지 페어",
  "endpoint-messengers": "엔드포인트 전령",
  "request-courier": "요청 배달부",
  "portal-wardens": "포털 수문장",
  "gateway-guardian": "게이트웨이 수호자",
  "script-snake": "스크립트 뱀",
  "library-coil": "라이브러리 코일",
  "data-coil": "데이터 코일",
  "automation-engine": "자동화 엔진",
  "automation-seraph": "자동화 세라프",
  "query-mole": "쿼리 두더지",
  "table-keeper": "테이블 지킴이",
  "join-mason": "조인 석공",
  "schema-warden": "스키마 감시자",
  "transaction-archivist": "트랜잭션 기록관",
  "packet-crab": "패킷 게",
  "router-weaver": "라우터 위버",
  "packet-relay": "패킷 릴레이",
  "network-orchestrator": "네트워크 지휘자",
  "protocol-nexus": "프로토콜 넥서스",
  "check-scout": "체크 정찰병",
  "case-inspector": "케이스 조사관",
  "assertion-hound": "어서션 하운드",
  "suite-guardian": "테스트 스위트 수호자",
  "regression-sentinel": "회귀 파수꾼",
  "key-scale": "키 스케일",
  "identity-keeper": "아이덴티티 지킴이",
  "identity-keywarden": "인증 키 감시자",
  "access-bastion": "접근 보루",
  "zero-trust-bastion": "제로 트러스트 보루",
  "image-whale": "이미지 고래",
  "container-tug": "컨테이너 예인선",
  "container-carrier": "컨테이너 운반선",
  "registry-carrier": "레지스트리 운반선",
  "harbor-leviathan": "항구 레비아탄",
  "build-runner": "빌드 러너",
  "test-relay": "테스트 릴레이",
  "pipeline-relay": "파이프라인 릴레이",
  "deployment-conductor": "배포 지휘자",
  "release-conductor": "릴리스 지휘자",
  "pod-cadet": "파드 생도",
  "cluster-pilot": "클러스터 조종사",
  "pod-helmsman": "파드 항해사",
  "fleet-commander": "플릿 지휘관",
  "cluster-admiral": "클러스터 제독",
  "resource-cloud": "리소스 구름",
  "plan-builder": "플랜 빌더",
  "blueprint-builder": "블루프린트 빌더",
  "infrastructure-architect": "인프라 설계자",
  "infrastructure-titan": "인프라 타이탄",
  "signal-owlet": "시그널 아기 올빼미",
  "alert-scout": "알림 정찰병",
  "metric-watcher": "메트릭 감시자",
  "telemetry-seer": "텔레메트리 예언자",
  "observability-oracle": "관측성 오라클",
  "state-sprout": "상태 새싹",
  "prop-pair": "프롭 페어",
  "component-weaver": "컴포넌트 위버",
  "hook-conductor": "훅 지휘자",
  "component-architect": "컴포넌트 설계자",
  "route-scout": "라우트 정찰병",
  "middleware-pair": "미들웨어 페어",
  "controller-warden": "컨트롤러 감시자",
  "framework-orchestrator": "프레임워크 지휘자",
  "service-guardian": "서비스 수호자",
  "droplet-runner": "데이터 방울 러너",
  "stream-courier": "스트림 배달부",
  "transform-engineer": "변환 기술자",
  "pipeline-conductor": "파이프라인 지휘자",
  "flow-architect": "플로 설계자",
  "task-spinner": "태스크 스피너",
  "dependency-linker": "의존성 링커",
  "retry-weaver": "재시도 위버",
  "schedule-conductor": "스케줄 지휘자",
  "workflow-maestro": "워크플로 마에스트로",
  "sample-owl": "표본 올빼미",
  "probability-reader": "확률 해석가",
  "distribution-scholar": "분포 학자",
  "variance-oracle": "분산 오라클",
  "inference-guardian": "추론 수호자",
  "bar-chameleon": "막대 카멜레온",
  "chart-caster": "차트 캐스터",
  "plot-artisan": "플롯 장인",
  "dashboard-storyteller": "대시보드 이야기꾼",
  "insight-prism": "인사이트 프리즘",
  "metric-firefly": "메트릭 반딧불이",
  "report-scout": "리포트 정찰병",
  "dashboard-keeper": "대시보드 지킴이",
  "kpi-oracle": "KPI 오라클",
  "decision-guardian": "의사결정 수호자",
});

export function careerMonsterName(id: string): LocalizedText {
  const name = CAREER_MONSTER_NAMES[id];
  if (!name) throw new Error(`Missing localized career monster name: ${id}`);
  return name;
}
